### ISSUE TITLE
Starts but nothing in the menubar

### ISSUE THREAD

**Issue by dooreelko** [n0shake/Clocker#84]
In case this is relevant, this is the only output in the termnial:

2021-02-02 11:27:39.060 Clocker[30729:103896] *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (Clocker.TimezoneData) for key (root) because no class named "Clocker.TimezoneData" was found; the class needs to be defined in source code or linked in from a library (ensure the class is part of the correct target). If the class was renamed, use setClassName:forClass: to add a class translation mapping to NSKeyedUnarchiver

**Comment by dooreelko** [comment]
I suspect i fixed the store contents with this, but since it doesn't happen anymore ¯\_(ツ)_/¯

```
:100644 100644 8259629 0000000 M        Clocker/CoreModelKit/Sources/CoreModelKit/TimezoneData.swift

diff --git a/Clocker/CoreModelKit/Sources/CoreModelKit/TimezoneData.swift b/Clocker/CoreModelKit/Sources/CoreModelKit/TimezoneData.swift
index 8259629..130fc9a 100644
--- a/Clocker/CoreModelKit/Sources/CoreModelKit/TimezoneData.swift
+++ b/Clocker/CoreModelKit/Sources/CoreModelKit/TimezoneData.swift
@@ -177,6 +177,8 @@ public class TimezoneData: NSObject, NSCoding {
             return TimezoneData()
         }

+        NSKeyedUnarchiver.setClass(CoreModelKit.TimezoneData.classForKeyedUnarchiver(), forClassName: "Clocker.TimezoneData")
+
         if let timezoneObject = NSKeyedUnarchiver.unarchiveObject(with: dataObject) as? TimezoneData {
             return timezoneObject
         }
```

**Comment by nathanurwinpgs** [comment]
Same thing happening to me:

```bash
$ /Applications/Clocker.app/Contents/MacOS/Clocker
2021-02-02 06:43:03.804 Clocker[3362:12416] *** -[NSKeyedUnarchiver decodeObjectForKey:]: cannot decode object of class (Clocker.TimezoneData) for key (root); the class may be defined in source code or a library that is not linked
```

**Comment by lsloan** [comment]
I don't have any log info to support it like the others above, but after I let Clocker get an update from the Mac App Store, it would no longer work.

I ended up going to a terminal to kill the current process, deleting the app, then downloading Clocker.app.zip from the [Releases](https://github.com/n0shake/Clocker/releases) section of this repo.  Now it works, but it looks like some of my settings aren't quite right.  I'll try to update them and see what happens.

**Comment by n0shake** [comment]
Looking!!

**Comment by n0shake** [comment]
Alright, found the issue. This should only happen to users who jumped directly from v20.10.03 -> v21.02.02 and missed the versions in between. I'll have the fix pushed to App Store soon.

**Comment by security-prince** [comment]
> Alright, found the issue. This should only happen to users who skipped v20.10.04. I'll have the fix pushed to App Store soon.

I am still facing this issue on 21.02.02 on MAC OS 10.15.7, I tried force quitting and restarting but won't work

**Comment by n0shake** [comment]
@security-prince The update hasn't been pushed to the App Store. Once it is, you can update which should resolve the issue. I'll keep posting updates here. In the meanwhile, here's a hacky workaround:

1. Make sure Clocker is closed (force quit through Activity Monitor if necessary)
2. Open up the Terminal app and type in the command: `defaults delete com.abhishek.Clocker`
3. Hit the return key
4. Restart Clocker

**This'll clean up your preferences, and you'll need to add the time zones again.**

**Comment by security-prince** [comment]
> @security-prince The update hasn't been pushed to the App Store. Once it is, you can update which should resolve the issue. I'll keep posting updates here. In the meanwhile, here's a hacky workaround:
> 
> 1. Make sure Clocker is closed (force quit through Activity Monitor if necessary)
> 2. Open up the Terminal app and type in the command: `defaults delete com.abhishek.Clocker`
> 3. Hit the return key
> 4. Restart Clocker
> 
> **This'll clean up your preferences, and you'll need to add the time zones again.** 

Thanks, will try this

**Comment by n0shake** [comment]
The update has been approved and pushed to the App Store. Closing!

**Comment by Drarok** [comment]
FYI, my time format setting got hosed somewhere amongst all this, I had to re-select `HH:mm` instead of `h:mm a` which appears to be the default.
